from collections.abc import Iterator

class Region:
    def __init__(self, a: int, b: int = ...) -> None: ...
    def empty(self) -> bool: ...

class Selection:
    def __iter__(self) -> Iterator[Region]: ...
    def __getitem__(self, index: int) -> Region: ...
    def add(self, region: Region) -> None: ...
    def clear(self) -> None: ...

class View:
    def change_count(self) -> int: ...
    def close(self) -> None: ...
    def is_read_only(self) -> bool: ...
    def replace(self, edit: object, region: Region, text: str) -> None: ...
    def run_command(
        self, command: str, args: dict[str, object] | None = ...
    ) -> None: ...
    def sel(self) -> Selection: ...
    def set_read_only(self, value: bool) -> None: ...
    def set_scratch(self, value: bool) -> None: ...
    def size(self) -> int: ...
    def substr(self, region: Region) -> str: ...

class Window:
    def new_file(self) -> View: ...

def active_window() -> Window: ...
