<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>__GROUP_ID__</groupId>
  <artifactId>__PROJECT_ID__.parent</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <tycho-version>__TYCHO_VERSION__</tycho-version>
    <maven.compiler.release>__JAVA_VERSION__</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <repositories>
    <repository>
      <id>eclipse-target</id>
      <layout>p2</layout>
      <url>__ECLIPSE_P2_REPOSITORY__</url>
    </repository>
  </repositories>

  <modules>
    <module>__PLUGIN_ID__</module>
    <module>__PLUGIN_ID__.tests</module>
    <module>__PLUGIN_ID__.feature</module>
    <module>__PLUGIN_ID__.repository</module>
  </modules>

  <build>
    <plugins>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-maven-plugin</artifactId>
        <version>${tycho-version}</version>
        <extensions>true</extensions>
      </plugin>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>target-platform-configuration</artifactId>
        <version>${tycho-version}</version>
        <configuration>
          <environments>
            <environment>
              <os>__TARGET_OS__</os>
              <ws>__TARGET_WS__</ws>
              <arch>__TARGET_ARCH__</arch>
            </environment>
          </environments>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
