name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: swift build -c release
